print("halo dunia")
print("nama saya *******")
print("aku suka makan duit rakyat")
print("cita-citaku adalah menjadi hengker")
print("tapi aku ga tau apa itu HTML")
print("yang aku tau hanya bagaimana cara hack facebook")
print("dan aku ingin membuat seluruh warga Indonesia ketar ketir :v")
print("aku selalu dibully karena aku suka memakai topeng anonymous")
print("dan aku selalu disebut cringe")
print("tapi aku tidak peduli apa kata mereka karena aku adalah hengker sejati")